-- ============================================================================
-- 谁是职场TOP（sszctop）数据库迁移脚本
-- 说明：只新增 sszctop 专属表、初始规则、游戏类型和后台菜单，不修改既有游戏业务表。
-- 脚本可重复执行；配置数据使用幂等更新。执行前请确认当前连接是目标数据库。
-- ============================================================================
-- 1. 维度、职业、排序、房间、成员、报告、日志七类专属表。
CREATE TABLE IF NOT EXISTS gkzh_sszctop_dimension (dimension_id bigint NOT NULL AUTO_INCREMENT, code varchar(32) NOT NULL, name varchar(64) NOT NULL, description varchar(1000) DEFAULT NULL, sort_order int NOT NULL DEFAULT 0, status char(1) NOT NULL DEFAULT '0', create_time datetime DEFAULT NULL, update_time datetime DEFAULT NULL, PRIMARY KEY(dimension_id), UNIQUE KEY uk_sszctop_dimension_code(code)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS gkzh_sszctop_career (career_id bigint NOT NULL AUTO_INCREMENT, name varchar(100) NOT NULL, major varchar(100) DEFAULT NULL, description varchar(1000) DEFAULT NULL, sort_order int NOT NULL DEFAULT 0, status char(1) NOT NULL DEFAULT '0', create_time datetime DEFAULT NULL, update_time datetime DEFAULT NULL, PRIMARY KEY(career_id), UNIQUE KEY uk_sszctop_career_name(name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS gkzh_sszctop_dimension_rank (rank_id bigint NOT NULL AUTO_INCREMENT, dimension_id bigint NOT NULL, career_id bigint NOT NULL, rank_order int NOT NULL, description varchar(2000) DEFAULT NULL, status char(1) NOT NULL DEFAULT '0', create_time datetime DEFAULT NULL, update_time datetime DEFAULT NULL, PRIMARY KEY(rank_id), UNIQUE KEY uk_sszctop_rank(dimension_id,career_id), UNIQUE KEY uk_sszctop_rank_order(dimension_id,rank_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS gkzh_sszctop_room (room_id bigint NOT NULL AUTO_INCREMENT, room_code varchar(12) NOT NULL, instance_id bigint NOT NULL, game_id bigint NOT NULL, owner_user_id bigint NOT NULL, mode varchar(10) NOT NULL, dimension_id bigint DEFAULT NULL, career_ids varchar(100) DEFAULT NULL, shared_order_ids varchar(100) DEFAULT NULL, order_version int NOT NULL DEFAULT 0, status varchar(16) NOT NULL DEFAULT 'waiting', create_time datetime DEFAULT NULL, update_time datetime DEFAULT NULL, finish_time datetime DEFAULT NULL, PRIMARY KEY(room_id), UNIQUE KEY uk_sszctop_room_code(room_code), KEY idx_sszctop_room_game(game_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS gkzh_sszctop_room_member (member_id bigint NOT NULL AUTO_INCREMENT, room_id bigint NOT NULL, user_id bigint NOT NULL, student_id bigint DEFAULT NULL, student_name varchar(100) DEFAULT NULL, student_no varchar(50) DEFAULT NULL, confirm_status varchar(16) NOT NULL DEFAULT 'waiting', confirm_version int DEFAULT NULL, confirmed_at datetime DEFAULT NULL, removed_reason varchar(100) DEFAULT NULL, removed_time datetime DEFAULT NULL, create_time datetime DEFAULT NULL, PRIMARY KEY(member_id), UNIQUE KEY uk_sszctop_room_user(room_id,user_id), KEY idx_sszctop_member_user(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS gkzh_sszctop_student_report (report_id bigint NOT NULL AUTO_INCREMENT, room_id bigint NOT NULL, instance_id bigint NOT NULL, game_id bigint NOT NULL, user_id bigint NOT NULL, student_id bigint DEFAULT NULL, dimension_snapshot text NOT NULL, careers_snapshot text NOT NULL, shared_order_snapshot varchar(100) NOT NULL, standard_order_snapshot varchar(100) NOT NULL, result varchar(16) NOT NULL, report_json text DEFAULT NULL, create_time datetime DEFAULT NULL, PRIMARY KEY(report_id), UNIQUE KEY uk_sszctop_report_room_user(room_id,user_id), KEY idx_sszctop_report_user_game(user_id,game_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- 房间日志使用房间号、用户和状态快照，房间主表销毁后仍可独立查询历史记录。
CREATE TABLE IF NOT EXISTS gkzh_sszctop_room_log (log_id bigint NOT NULL AUTO_INCREMENT, instance_id bigint NOT NULL, game_id bigint NOT NULL, room_id bigint NOT NULL, room_code varchar(12) NOT NULL, room_status varchar(16) DEFAULT NULL, user_id bigint DEFAULT NULL, student_id bigint DEFAULT NULL, student_name varchar(100) DEFAULT NULL, student_no varchar(50) DEFAULT NULL, event_type varchar(50) NOT NULL, content varchar(1000) DEFAULT NULL, create_time datetime DEFAULT NULL, PRIMARY KEY(log_id), KEY idx_sszctop_log_room(room_id,create_time), KEY idx_sszctop_log_game(game_id,create_time), KEY idx_sszctop_log_activity_user(instance_id,user_id,log_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 初始化七个维度；code 用于规则导入，name 用于后台和学生端展示。
INSERT INTO gkzh_sszctop_dimension(code,name,description,sort_order,status,create_time,update_time) VALUES
('steps','微信步数','反映职业日常行动量与工作场景的移动强度。',1,'0',NOW(),NOW()),('hours','工作时长','反映职业常见的周工作时长与生活节奏。',2,'0',NOW(),NOW()),('pressure','压力指数','反映责任、时效、风险及精神消耗的综合强度。',3,'0',NOW(),NOW()),('skill','技能门槛','反映准入资格、知识纵深和长期技能积累要求。',4,'0',NOW(),NOW()),('prospect','行业前景','反映技术变革、政策需求和职业发展空间。',5,'0',NOW(),NOW()),('social','社交强度','反映人际互动密度、沟通深度与关系维护要求。',6,'0',NOW(),NOW()),('travel','出差频率','反映工作场域跨度、行动半径和差旅节奏。',7,'0',NOW(),NOW()) ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description),sort_order=VALUES(sort_order),update_time=NOW();
-- 初始化十二个职业；职业名称具有唯一约束，便于跨环境导入排序关系。
INSERT INTO gkzh_sszctop_career(name,major,description,sort_order,status,create_time,update_time) VALUES
('人工智能工程师','数学','长时间编码、训练模型和调试算法，技术迭代快，行业需求强。',1,'0',NOW(),NOW()),('数据分析师','统计学','围绕取数、建模和报表支持业务决策，强调统计与业务理解。',2,'0',NOW(),NOW()),('临床医生','医学','承担诊疗、查房、夜班等工作，专业培养周期长且责任重大。',3,'0',NOW(),NOW()),('企业经理','管理学','通过会议、协调和决策推动团队目标，承担经营与团队责任。',4,'0',NOW(),NOW()),('新闻记者','新闻学','采访、现场报道和内容生产并重，需快速响应事件与信息变化。',5,'0',NOW(),NOW()),('律师','法学','围绕客户、证据、合同和庭审提供法律服务，专业性和时限要求高。',6,'0',NOW(),NOW()),('金融分析师','金融学','以研究、估值和报告为核心，服务投资与金融决策。',7,'0',NOW(),NOW()),('中小学教师','教育学','承担教学、备课、学生管理和家校沟通等持续性工作。',8,'0',NOW(),NOW()),('农业技术推广员','农学','深入田间开展技术指导、培训和成果转化，外勤场景丰富。',9,'0',NOW(),NOW()),('视觉设计师','艺术学','以设计表达、软件制作和反复修改为主，需要连续专注创作。',10,'0',NOW(),NOW()),('博物馆讲解员','历史学','在展厅中面向观众开展规范化讲解，工作环境和时间相对稳定。',11,'0',NOW(),NOW()),('综合管理类公务员','法学','从事机关综合协调、文秘会务和政策研究，以办公室工作为主。',12,'0',NOW(),NOW()) ON DUPLICATE KEY UPDATE major=VALUES(major),description=VALUES(description),sort_order=VALUES(sort_order),update_time=NOW();
-- 排名用维度编码和职业名称解析，确保不同环境的自增 ID 不同也能正确导入。
INSERT INTO gkzh_sszctop_dimension_rank(dimension_id,career_id,rank_order,description,status,create_time,update_time)
SELECT d.dimension_id,c.career_id,x.rank_order,CONCAT(d.name,'下的职业认知说明：',c.description),'0',NOW(),NOW() FROM (
SELECT 'steps' code,'农业技术推广员' name,1 rank_order UNION ALL SELECT 'steps','博物馆讲解员',2 UNION ALL SELECT 'steps','新闻记者',3 UNION ALL SELECT 'steps','临床医生',4 UNION ALL SELECT 'steps','中小学教师',5 UNION ALL SELECT 'steps','企业经理',6 UNION ALL SELECT 'steps','律师',7 UNION ALL SELECT 'steps','综合管理类公务员',8 UNION ALL SELECT 'steps','金融分析师',9 UNION ALL SELECT 'steps','人工智能工程师',10 UNION ALL SELECT 'steps','数据分析师',11 UNION ALL SELECT 'steps','视觉设计师',12 UNION ALL
SELECT 'hours','金融分析师',1 UNION ALL SELECT 'hours','临床医生',2 UNION ALL SELECT 'hours','律师',3 UNION ALL SELECT 'hours','新闻记者',4 UNION ALL SELECT 'hours','人工智能工程师',5 UNION ALL SELECT 'hours','企业经理',6 UNION ALL SELECT 'hours','中小学教师',7 UNION ALL SELECT 'hours','数据分析师',8 UNION ALL SELECT 'hours','视觉设计师',9 UNION ALL SELECT 'hours','综合管理类公务员',10 UNION ALL SELECT 'hours','农业技术推广员',11 UNION ALL SELECT 'hours','博物馆讲解员',12 UNION ALL
SELECT 'pressure','临床医生',1 UNION ALL SELECT 'pressure','金融分析师',2 UNION ALL SELECT 'pressure','律师',3 UNION ALL SELECT 'pressure','新闻记者',4 UNION ALL SELECT 'pressure','企业经理',5 UNION ALL SELECT 'pressure','人工智能工程师',6 UNION ALL SELECT 'pressure','中小学教师',7 UNION ALL SELECT 'pressure','数据分析师',8 UNION ALL SELECT 'pressure','综合管理类公务员',9 UNION ALL SELECT 'pressure','视觉设计师',10 UNION ALL SELECT 'pressure','农业技术推广员',11 UNION ALL SELECT 'pressure','博物馆讲解员',12 UNION ALL
SELECT 'skill','临床医生',1 UNION ALL SELECT 'skill','金融分析师',2 UNION ALL SELECT 'skill','律师',3 UNION ALL SELECT 'skill','人工智能工程师',4 UNION ALL SELECT 'skill','数据分析师',5 UNION ALL SELECT 'skill','中小学教师',6 UNION ALL SELECT 'skill','企业经理',7 UNION ALL SELECT 'skill','视觉设计师',8 UNION ALL SELECT 'skill','新闻记者',9 UNION ALL SELECT 'skill','农业技术推广员',10 UNION ALL SELECT 'skill','综合管理类公务员',11 UNION ALL SELECT 'skill','博物馆讲解员',12 UNION ALL
SELECT 'prospect','人工智能工程师',1 UNION ALL SELECT 'prospect','数据分析师',2 UNION ALL SELECT 'prospect','金融分析师',3 UNION ALL SELECT 'prospect','企业经理',4 UNION ALL SELECT 'prospect','临床医生',5 UNION ALL SELECT 'prospect','律师',6 UNION ALL SELECT 'prospect','农业技术推广员',7 UNION ALL SELECT 'prospect','综合管理类公务员',8 UNION ALL SELECT 'prospect','中小学教师',9 UNION ALL SELECT 'prospect','视觉设计师',10 UNION ALL SELECT 'prospect','新闻记者',11 UNION ALL SELECT 'prospect','博物馆讲解员',12 UNION ALL
SELECT 'social','新闻记者',1 UNION ALL SELECT 'social','企业经理',2 UNION ALL SELECT 'social','临床医生',3 UNION ALL SELECT 'social','律师',4 UNION ALL SELECT 'social','中小学教师',5 UNION ALL SELECT 'social','农业技术推广员',6 UNION ALL SELECT 'social','综合管理类公务员',7 UNION ALL SELECT 'social','博物馆讲解员',8 UNION ALL SELECT 'social','金融分析师',9 UNION ALL SELECT 'social','数据分析师',10 UNION ALL SELECT 'social','人工智能工程师',11 UNION ALL SELECT 'social','视觉设计师',12 UNION ALL
SELECT 'travel','农业技术推广员',1 UNION ALL SELECT 'travel','金融分析师',2 UNION ALL SELECT 'travel','企业经理',3 UNION ALL SELECT 'travel','新闻记者',4 UNION ALL SELECT 'travel','人工智能工程师',5 UNION ALL SELECT 'travel','律师',6 UNION ALL SELECT 'travel','临床医生',7 UNION ALL SELECT 'travel','数据分析师',8 UNION ALL SELECT 'travel','视觉设计师',9 UNION ALL SELECT 'travel','综合管理类公务员',10 UNION ALL SELECT 'travel','中小学教师',11 UNION ALL SELECT 'travel','博物馆讲解员',12) x JOIN gkzh_sszctop_dimension d ON d.code=x.code JOIN gkzh_sszctop_career c ON c.name=x.name
ON DUPLICATE KEY UPDATE rank_order=VALUES(rank_order),description=VALUES(description),status='0',update_time=NOW();
INSERT INTO gkzh_game_type(game_type,game_name,front_component,result_type,status,create_time,update_time) VALUES('sszctop','谁是职场TOP','pages/sszctop/index','complete','0',NOW(),NOW()) ON DUPLICATE KEY UPDATE game_name=VALUES(game_name),front_component=VALUES(front_component),status='0',update_time=NOW();

-- 游戏配置登记：谁是职场TOP是具体游戏，归入“合作”类别；后台页面只展示中文类别。
INSERT INTO gkzh_game_config(game_type,category,route,game_name,description,config_json,status,create_time,update_time)
SELECT 'sszctop','cooperation','sszctop','谁是职场TOP','谁是职场TOP合作类游戏','{}','0',NOW(),NOW()
WHERE NOT EXISTS (SELECT 1 FROM gkzh_game_config WHERE game_type='sszctop');
UPDATE gkzh_game_config SET category='cooperation',game_name='谁是职场TOP',status='0',update_time=NOW() WHERE game_type='sszctop';

-- 注册活动周游戏类型，前端组件路径与后端 gameType 保持一致。
-- 后台配置菜单：仅新增菜单与管理员授权，不改动现有菜单权限。
INSERT IGNORE INTO sys_menu(menu_id,menu_name,parent_id,order_num,path,component,query,route_name,is_frame,is_cache,menu_type,visible,status,perms,icon,create_by,create_time,update_by,update_time,remark) VALUES
(2300,'谁是职场TOP',0,20,'sszctop','', '', '',1,0,'M','0','0','','star','admin',NOW(),'admin',NOW(),'职业认知游戏目录'),
(2301,'游戏配置',2300,1,'config','sszctop/config/index','', '',1,0,'C','0','0','sszctop:config:list','edit','admin',NOW(),'admin',NOW(),'维度、职业、排序文案'),
(2302,'配置新增',2301,1,'#','', '', '',1,0,'F','0','0','sszctop:config:add','#','admin',NOW(),'admin',NOW(),''),
(2303,'配置修改',2301,2,'#','', '', '',1,0,'F','0','0','sszctop:config:edit','#','admin',NOW(),'admin',NOW(),''),
(2304,'房间日志',2300,2,'room-log','sszctop/config/index','', '',1,0,'C','0','0','sszctop:log:list','documentation','admin',NOW(),'admin',NOW(),'房间游玩日志');
INSERT IGNORE INTO sys_role_menu(role_id,menu_id) VALUES(1,2300),(1,2301),(1,2302),(1,2303),(1,2304);

-- 菜单层级：游戏配置 -> 谁是职场TOP -> 四个配置页面。
UPDATE sys_menu SET parent_id=2235,order_num=20,menu_name='谁是职场TOP',path='sszctop',component='',menu_type='C',perms='sszctop:config:list',icon='star',update_time=NOW() WHERE menu_id=2300;
UPDATE sys_menu SET parent_id=2300,order_num=1,menu_name='维度设置',path='dimension',component='sszctop/config/index',query='{"tab":"dimension"}',menu_type='C',perms='sszctop:config:list',update_time=NOW() WHERE menu_id=2301;
UPDATE sys_menu SET parent_id=2300,order_num=2,menu_name='职业配置',path='career',component='sszctop/config/index',query='{"tab":"career"}',menu_type='C',perms='sszctop:config:list',update_time=NOW() WHERE menu_id=2302;
UPDATE sys_menu SET parent_id=2300,order_num=3,menu_name='维度排序及文案',path='rank',component='sszctop/config/index',query='{"tab":"rank"}',menu_type='C',perms='sszctop:config:list',update_time=NOW() WHERE menu_id=2303;
UPDATE sys_menu SET parent_id=2300,order_num=4,menu_name='房间游玩日志',path='room-log',component='sszctop/config/index',query='{"tab":"log"}',menu_type='C',perms='sszctop:log:list',update_time=NOW() WHERE menu_id=2304;
INSERT IGNORE INTO sys_menu(menu_id,menu_name,parent_id,order_num,path,component,query,route_name,is_frame,is_cache,menu_type,visible,status,perms,icon,create_by,create_time,update_by,update_time,remark) VALUES
(2305,'配置新增',2300,10,'#','','','',1,0,'F','1','0','sszctop:config:add','#','admin',NOW(),'admin',NOW(),''),
(2306,'配置修改',2300,11,'#','','','',1,0,'F','1','0','sszctop:config:edit','#','admin',NOW(),'admin',NOW(),'');
INSERT IGNORE INTO sys_role_menu(role_id,menu_id) VALUES(1,2305),(1,2306);
