-- ============================================================================
-- sszctop 维度排序说明同步脚本
-- 来源：职业认知——谁是职场TOP 介绍.docx 各维度解释部分的职业说明。
-- 说明：仅更新排序说明，不修改维度、职业、正确名次及其它模块数据；可重复执行。
-- ============================================================================
SET NAMES utf8mb4;
-- 维度：微信步数（steps）
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='常年奔波于田间地头、种植基地、农户庭院和乡镇农技站，需要实地察看作物长势、指导病虫害防治，有时一天走访多个村庄。户外工作、步行距离长、步数极其可观，日均通常在 15000 步以上，稳居第一。',r.update_time=NOW() WHERE d.code='steps' AND c.name='农业技术推广员';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='全天带队穿梭于各个展厅，一边行走一边讲解，每场讲解持续数十分钟，日复一日。工作时间内几乎不存在坐下休息的时间，相当于室内“巡馆式”行走。日均步数常达 12000—15000 步，堪比导游。',r.update_time=NOW() WHERE d.code='steps' AND c.name='博物馆讲解员';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='外勤记者需要赶赴现场、追拍画面、采访不同对象，时常辗转于城市各处甚至外出远郊，步数累积迅速。即使后期需伏案写稿，但出外勤时的行走强度拉高了整体均值。日均步数一般约 10000—12000 步。',r.update_time=NOW() WHERE d.code='steps' AND c.name='新闻记者';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='病房医生查房、会诊、前往各科室处理病情，住院医师更是整日在病区、护士站、检验科之间折返；虽然门诊医生相对久坐，但大量住院部与急诊医生的高强度走动使整体均值处于较高水平，日均 8000—11000 步。',r.update_time=NOW() WHERE d.code='steps' AND c.name='临床医生';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='课堂内来回巡视、板书讲解，课间穿梭于教室和办公室，班主任还需跑操、带队放学等。虽不是持续高强度，但站立和行走贯穿全天，几乎没有“久坐不动”的时段，日均步数多在 7000—9000 步。',r.update_time=NOW() WHERE d.code='steps' AND c.name='中小学教师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='管理工作需巡视办公区、生产车间或门店，也要频繁进出会议室、接待客户、出差考察。但因会议和案头工作占一定比重，整体行走量不如前五者。日均约 6000—8000 步，视行业有所浮动。',r.update_time=NOW() WHERE d.code='steps' AND c.name='企业经理';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='诉讼律师需要往返法院、看守所或客户单位，调查取证时也有较多室外行走；但非诉和事务性律师有大量卷宗研读、文书起草等久坐时间，整体平均行走量被拉低。日均步数大致在 5000—7000 步。',r.update_time=NOW() WHERE d.code='steps' AND c.name='律师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='此处指机关办公室从事综合协调、文秘会务、政策研究的公务员，以室内办公为主，多数时间在工位、会议室、打印机之间短距离移动。虽然偶有外勤，但久坐特征明显，日均步数约 4000—6000 步。',r.update_time=NOW() WHERE d.code='steps' AND c.name='综合管理类公务员';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='主要面对屏幕处理数据、撰写报告、参加策略会，工作形态以久坐研究为核心，走动通常只发生在午餐、去洗手间或短时会议间隙。日均步数普遍较低，约 3000—4500 步。',r.update_time=NOW() WHERE d.code='steps' AND c.name='金融分析师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='典型的技术研发岗位，长时间面对电脑编码、训练模型、调试算法，开会也多以线上或坐下来完成。由于任务高度沉浸，主动起身次数很少，日均步数一般 2500—4000 步。',r.update_time=NOW() WHERE d.code='steps' AND c.name='人工智能工程师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='同样以取数、建模、制作报表和跨部门沟通为主，沟通大多通过即时通讯或会议室小范围移动完成，行走场景极为有限。和人工智能工程师相近，整体日均步数在 2500—3500 步左右，有时甚至更低。',r.update_time=NOW() WHERE d.code='steps' AND c.name='数据分析师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='从构思草图到细节调色，全程绑定于电脑前，需要长时间连续专注，连续数小时不挪位很常见。哪怕去接水、上卫生间的频次都容易被压缩，是典型的“久坐不动型”职业，日均步数通常在 2000—3000 步，为12个职业中最低。',r.update_time=NOW() WHERE d.code='steps' AND c.name='视觉设计师';
-- 维度：工作时长（hours）
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='（这里主要指卖方分析师、投行分析师等）以“每周100小时”的极端工时著称，项目期连轴转、通宵赶材料是常态，平均每周工时可达80小时以上，远超其他职业，稳居第一。',r.update_time=NOW() WHERE d.code='hours' AND c.name='金融分析师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='查房、手术、夜班、病历文书层层叠加，住院医师阶段更是长期超负荷，日均工作12小时常见，周均工时普遍在60—80小时，工作量极为饱和。',r.update_time=NOW() WHERE d.code='hours' AND c.name='临床医生';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='诉讼与非诉律师均面临严苛的计费工时与多重截止日压力，调查取证、开庭准备、合同审核经常挤占休息时间，周均工时多在55—70小时。',r.update_time=NOW() WHERE d.code='hours' AND c.name='律师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='突发报道和深度调查要求全天候响应，截稿压力下日夜兼程是家常便饭，每日工作时长常超10小时，周均约50—65小时，且时间高度碎片化。',r.update_time=NOW() WHERE d.code='hours' AND c.name='新闻记者';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='互联网与科技行业“996”乃至更长的研发周期较为普遍，赶版本、调模型时加班密集，周均工时普遍在50—60小时，部分企业可达70小时以上。',r.update_time=NOW() WHERE d.code='hours' AND c.name='人工智能工程师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='中高层管理者会议密集、决策链长、业绩责任重，隐形工作时间（差旅、应酬、思考型加班）很多，日均工作常超10小时，周均约50—60小时。',r.update_time=NOW() WHERE d.code='hours' AND c.name='企业经理';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='日常教学仅冰山一角，备课、批改、学生管理、家校沟通等“隐形工作”大量挤占业余时间，学期内早出晚归，日均工作9—10小时，周均45—55小时。',r.update_time=NOW() WHERE d.code='hours' AND c.name='中小学教师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='业务需求频繁变动，取数、建模、报表需快速响应，项目冲刺期加班是常态，但整体强度略低于前端研发，周均工时约45—50小时。',r.update_time=NOW() WHERE d.code='hours' AND c.name='数据分析师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='乙方与互联网设计岗位常为需求反复修改、多轮评审买单，赶稿期连续熬夜，但因项目间隙有缓冲，整体周均工时约45小时左右。',r.update_time=NOW() WHERE d.code='hours' AND c.name='视觉设计师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='以机关办公室工作为主，大多数岗位遵循标准工时，虽偶有迎检、会议筹备等加班，但总体工作时间规律，周均约40—45小时。',r.update_time=NOW() WHERE d.code='hours' AND c.name='综合管理类公务员';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='田间指导虽需奔波，但多依农时和天气安排，作业时间较有弹性，无重大灾情或项目时基本维持正常下班，周均约40小时。',r.update_time=NOW() WHERE d.code='hours' AND c.name='农业技术推广员';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='严格按开闭馆时间和排班表运行，每场讲解时长固定，闭馆即结束工作，几乎不存在加班，周均工时约35—40小时，为12个职业中最短。',r.update_time=NOW() WHERE d.code='hours' AND c.name='博物馆讲解员';
-- 维度：压力指数（pressure）
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='直接面对生命安危，诊断与治疗容错率极低；长期超负荷运转，夜班扰乱生理节律；同时承受科研、晋升与医患关系多重挤压，压力指数稳居首位。',r.update_time=NOW() WHERE d.code='pressure' AND c.name='临床医生';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='市场瞬息万变，报告精准度直接关联巨额资金决策；极端的时效压迫与业绩排名，配合几乎全年无休的高强度运转，精神长期处于高压敏锐状态。',r.update_time=NOW() WHERE d.code='pressure' AND c.name='金融分析师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='诉讼胜负、交易成败往往取决于细节与时限，客户预期严苛且后果不可逆；计费工时的束缚与持续的知识更新，共同构成重度职业焦虑。',r.update_time=NOW() WHERE d.code='pressure' AND c.name='律师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='截稿时效与事实准确性的双重博弈，深度报道常伴人身风险与法律边界试探；信息的不确定性、持续在线的抢独家状态，令神经难以放松。',r.update_time=NOW() WHERE d.code='pressure' AND c.name='新闻记者';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='背负明确的业绩指标与团队存续责任，决策后果直接且迅速反馈；市场竞争、人际冲突与随时待命的隐形消耗，形成持续性的综合压力。',r.update_time=NOW() WHERE d.code='pressure' AND c.name='企业经理';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='技术迭代飞快，模型性能与项目交付存在硬性指标；高强度脑力输出叠加行业“优化”焦虑，使得长期处于技术竞跑与不确定性压力之中。',r.update_time=NOW() WHERE d.code='pressure' AND c.name='人工智能工程师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='学生安全责任如山，成绩提升与社会期待构成双向负担；隐形工作时长与家校矛盾调和，致使情绪劳动强度居高不下。',r.update_time=NOW() WHERE d.code='pressure' AND c.name='中小学教师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='数据准确性与时效性关系业务决策，需求频繁变动易形成“被动应答”的压迫感；技术保鲜与价值证明的压力持续并存。',r.update_time=NOW() WHERE d.code='pressure' AND c.name='数据分析师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='流程规范严密、问责体系清晰，层级协调与程序合规带来审慎压力；突发任务与迎检考核使心理紧绷，但整体波动较缓。',r.update_time=NOW() WHERE d.code='pressure' AND c.name='综合管理类公务员';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='创意主观评判反复迭代，修改无常易引发自我怀疑；交稿节点的累积式突击，带来阶段性高压，但无直接安全或重大经济损失风险。',r.update_time=NOW() WHERE d.code='pressure' AND c.name='视觉设计师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='工作对象依赖自然条件，成果反馈周期长且影响因子分散；指导责任虽有，但节奏可调、弹性较大，整体压力较为和缓。',r.update_time=NOW() WHERE d.code='pressure' AND c.name='农业技术推广员';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='工作内容固定、环境稳定，讲解任务按固定排班与脚本执行；无硬性指标考核与即时风险，心理负荷在12个职业中最轻。',r.update_time=NOW() WHERE d.code='pressure' AND c.name='博物馆讲解员';
-- 维度：技能门槛（skill）
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='培养周期最长，需完成5-8年本硕博教育、3年住院医师规范化培训及终身继续教育；执业医师资格通过率严格，知识体系横跨基础医学与临床实践，技能累积曲线极为陡峭，门槛稳居首位。',r.update_time=NOW() WHERE d.code='skill' AND c.name='临床医生';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='以CFA持证等标杆为代表，知识覆盖财务分析、投资组合、衍生品定价等宽泛领域；头部机构普遍要求顶尖院校硕博背景，实习与建模实战经验层层筛选，复合型能力门槛极高。',r.update_time=NOW() WHERE d.code='skill' AND c.name='金融分析师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='法律职业资格考试（原司法考试）以低通过率和高知识密度著称，叠加逻辑思辨、文书写作与庭审应变的多重素养；专业领域分化后，还需在细分赛道长期深耕才能独立执业。',r.update_time=NOW() WHERE d.code='skill' AND c.name='律师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='数学基础、算法功底与工程落地能力缺一不可，前沿模型迭代迫使持续高强度学习；头部岗位通常要求计算机或统计相关硕博学历，以及高质量项目或论文积累，壁垒十分硬核。',r.update_time=NOW() WHERE d.code='skill' AND c.name='人工智能工程师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='需掌握统计学、SQL、Python及商业洞察的交叉应用；入门的工具学习相对平缓，但进阶为数据科学家需深厚量化背景，整体技能门槛呈阶梯式分布，平均处于中高位。',r.update_time=NOW() WHERE d.code='skill' AND c.name='数据分析师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='教师资格证为法定准入门槛，学科知识与教学教法需融合打磨；教师编制考试竞争激烈，课堂管理与教育心理等隐性技能，需数轮教学周期方能纯熟。',r.update_time=NOW() WHERE d.code='skill' AND c.name='中小学教师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='无统一硬性资格证，但管理幅度、战略思维、财务与人事等多维能力均需长期实战积累；晋升通道普遍依赖业绩验证与行业沉淀，经验门槛远高于学历门槛。',r.update_time=NOW() WHERE d.code='skill' AND c.name='企业经理';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='需系统掌握设计原理、软件工具链与审美表达，作品集是核心评判依据；入门技能可通过集中培训速成，但形成成熟设计语言需长期浸润，门槛外显而内深。',r.update_time=NOW() WHERE d.code='skill' AND c.name='视觉设计师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='新闻敏感度、采访突破与叙事写作需要专门训练，主流媒体多要求新闻传播学类学历；互联网时代还需叠加多媒体技能，但入门路径相对多元，整体门槛中等。',r.update_time=NOW() WHERE d.code='skill' AND c.name='新闻记者';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='通常要求农学类相关专业背景，需将实验室成果转化为田间可落地方案；技能强依赖于一线经验积累，但学科专业相对聚焦，入门知识范围较窄。',r.update_time=NOW() WHERE d.code='skill' AND c.name='农业技术推广员';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='公务员考试侧重通用能力（行测、申论），无特定专业硬性壁垒；岗位核心技能如公文处理、协调沟通等，大多通过入职后体系化培训与在岗实践习得。',r.update_time=NOW() WHERE d.code='skill' AND c.name='综合管理类公务员';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='需掌握展品知识与语言表达能力，普遍要求大专或本科学历；通过短期集中培训即可胜任基础讲解，无法律强制资格证书限制，入门门槛最为轻量。',r.update_time=NOW() WHERE d.code='skill' AND c.name='博物馆讲解员';
-- 维度：行业前景（prospect）
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='需求呈井喷式爆发，2026年春招岗位量同比增长超8倍，核心算法岗供需比仅为0.31，人才供不应求。未来五年专家级人才增长预测达85%，平均月薪超2万元，技术迭代驱动长期红利，前景稳居首位。',r.update_time=NOW() WHERE d.code='prospect' AND c.name='人工智能工程师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='大数据战略渗透各行各业，高端复合型人才持续稀缺，跨境数据分析师年薪可达25至50万元。未来五年大数据专家净增长预测高达110%，虽基础岗位受AI冲击，但进阶赛道广阔，整体前景强劲。',r.update_time=NOW() WHERE d.code='prospect' AND c.name='数据分析师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='金融与科技深度融合，金融科技工程师需求未来五年预计增长95%。行业薪酬涨幅以7.76%领跑各领域，CFA持证人在高端市场持续抢手，资本市场的复杂化为专业分析创造长期价值空间。',r.update_time=NOW() WHERE d.code='prospect' AND c.name='金融分析师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='战略型管理者的核心地位难以替代，企业转向“资深管理者加AI”的协作模式。经验壁垒深厚，顶级经理人薪酬可观，掌握AI工具和跨领域整合能力的管理者将享有持续的职业红利。',r.update_time=NOW() WHERE d.code='prospect' AND c.name='企业经理';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='人口老龄化与健康意识觉醒带来刚性需求，基层医疗人才缺口达28万，智慧医疗催生新岗位年增长45%。职业稳定性极强，收入稳健增长，但三甲医院竞争白热化，博士学历渐成基本门槛。',r.update_time=NOW() WHERE d.code='prospect' AND c.name='临床医生';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='从业人数激增至83万，行业竞争加剧，但专业化与涉外法律服务开辟高价值赛道，相关市场需求占比升至68%。涉外律师、数据合规律师等成为高薪方向，前景从规模扩张转向质量分化。',r.update_time=NOW() WHERE d.code='prospect' AND c.name='律师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='乡村振兴战略持续释放政策红利，国家提供定向培养与事业编制保障。虽薪资水平不突出，但岗位稳定性极高，在就业市场波动中展现出可靠的托底优势。',r.update_time=NOW() WHERE d.code='prospect' AND c.name='农业技术推广员';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='职业稳定性极强，在不确定性增大的就业市场中吸引力持续走高。薪资与晋升路径明确，事业单位薪酬涨幅约4.64%，虽增长平缓，但失业风险极低，社会认可度稳固。',r.update_time=NOW() WHERE d.code='prospect' AND c.name='综合管理类公务员';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='岗位需求从数量满足转向质量提升，部分学科教师仍紧缺，工资待遇有政策建议支撑。但学龄人口减少带来的生源压力与岗位竞争加剧，构成长期挑战，前景稳中有变。',r.update_time=NOW() WHERE d.code='prospect' AND c.name='中小学教师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='就业率达89%，传统UI岗需求收缩，市场分化明显。具备AI工具、三维设计等多技能的复合型人才需求上升，能否转型为会用AI的创意策动者，是职业前景的分水岭。',r.update_time=NOW() WHERE d.code='prospect' AND c.name='视觉设计师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='传统媒体岗位持续缩减，行业转型阵痛明显。全媒体记者、具备数据分析能力的专家型人才尚存发展空间，整体赛道收窄，出路在于向新媒体与企业传播等领域积极拓展。',r.update_time=NOW() WHERE d.code='prospect' AND c.name='新闻记者';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='文博热虽带动一定需求，但岗位总量极为有限，近年统计招聘职位数仅三四百人。薪资天花板较低，职业晋升通道窄，更多依托情怀与价值感支撑，前景在12个职业中最受限。',r.update_time=NOW() WHERE d.code='prospect' AND c.name='博物馆讲解员';
-- 维度：社交强度（social）
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='记者的核心生产力是采访与信息获取，全天候主动寻找陌生人建立连接，从线人、受访者到专家资源圈均需持续经营，沟通伴随高强度目的性与即时应变，社交强度居首。',r.update_time=NOW() WHERE d.code='social' AND c.name='新闻记者';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='管理的本质是通过他人完成工作，日程被会议、谈判、跨部门协调和商务应酬填满，向上汇报、向下激励、对外博弈多维交织，几乎全程处于人际互动状态。',r.update_time=NOW() WHERE d.code='social' AND c.name='企业经理';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='每日面对大量患者及家属，需在极短时间内完成问诊、解释、安抚和告知，同时与护士、医技、行政等团队高频协作，沟通密度和情绪负载极高。',r.update_time=NOW() WHERE d.code='social' AND c.name='临床医生';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='客户接待、调查取证、谈判交锋与出庭辩论构成工作主轴，需精准解读对方意图并输出观点，社交兼具策略性与说服力，深度互动贯穿项目始终。',r.update_time=NOW() WHERE d.code='social' AND c.name='律师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='课堂讲授、课下辅导、学生谈话与家校沟通是每日必修课，班主任角色更须精细化关注每个孩子并向家长反馈，持续性、重复性的高强度沟通贯穿学期。',r.update_time=NOW() WHERE d.code='social' AND c.name='中小学教师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='走村串户、田间指导、培训示范是工作常态，需面对不同年龄和认知层次的农户反复讲解、演示和答疑，建立信任依赖长期的人际浸润。',r.update_time=NOW() WHERE d.code='social' AND c.name='农业技术推广员';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='机关运行依赖上传下达和横向协调，日常应对电话、会议、汇报、材料会商等公务交际，需要维持广泛的内部工作关系，社交频率稳定但多限于体制内规范。',r.update_time=NOW() WHERE d.code='social' AND c.name='综合管理类公务员';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='以标准化知识输出为主，每场讲解虽有互动但多为短暂问答，社交对象流动性大、重复性高，沟通深度和关系维系要求相对较低。',r.update_time=NOW() WHERE d.code='social' AND c.name='博物馆讲解员';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='主要精力投入数据处理与报告撰写，虽然需要与客户、管理层或上市公司进行阶段性沟通，但整体以案头研究为主，社交并非核心生产力。',r.update_time=NOW() WHERE d.code='social' AND c.name='金融分析师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='工作围绕取数、建模和报表展开，多数需求通过线上工具接收和交付，跨部门沟通通常围绕明确的业务需求，社交广度与深度较为有限。',r.update_time=NOW() WHERE d.code='social' AND c.name='数据分析师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='研发属性强，长时间聚焦代码与算法调试，团队内虽有协作但形式多为技术评审或文档沟通，社交频次和必需程度在技术职业中处于低位。',r.update_time=NOW() WHERE d.code='social' AND c.name='人工智能工程师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='创作过程要求独立、连贯的专注时间，需求的承接与反馈多通过文档或简短会议完成，沟通方式高度结构化，社交强度为12个职业中最低。',r.update_time=NOW() WHERE d.code='social' AND c.name='视觉设计师';
-- 维度：出差频率（travel）
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='以实地指导、示范推广为核心，常年走村串户，深入田间地头。据相关招聘要求，该岗位年均出差天数可达150-200天，每月出差20-25天为常态，频率稳居各职业之首。',r.update_time=NOW() WHERE d.code='travel' AND c.name='农业技术推广员';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='金融业是出差频率最高的行业之一。尤其投行、卖方分析师等岗位，项目需要频繁赴客户公司进行尽职调查、路演和会议。有报告显示，从业者年均出差次数高，且多为短期高频差旅，位列高频出差前列。',r.update_time=NOW() WHERE d.code='travel' AND c.name='金融分析师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='中高层管理人员差旅是工作常态，高管和市场岗位被评为“最能飞”的群体。差旅目的包括业务拓展、客户关系维护、内部管理及行业会议等，管理岗位在出差人群中占比显著偏高。',r.update_time=NOW() WHERE d.code='travel' AND c.name='企业经理';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='追求新闻现场是记者工作的核心，尤其是调查记者、摄影记者，常需奔赴异地突发事件、会议或进行深度调研。记录显示，忙碌时月出差天数可达20天以上，行程密集。',r.update_time=NOW() WHERE d.code='travel' AND c.name='新闻记者';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='工程师群体位列“年度出差最多人群”首位。需出差支持系统部署、客户培训或异地项目开发。单次出差约10-15天，跨国项目差旅频率更高，部分岗位年累计出差可达7个月。',r.update_time=NOW() WHERE d.code='travel' AND c.name='人工智能工程师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='职业特性决定必须为客户的异地案件奔走。非诉律师比诉讼律师年均出差更多。出差天数分化明显，虽多数在30天以内，但业务广泛的律师年均飞行可达80-90次。',r.update_time=NOW() WHERE d.code='travel' AND c.name='律师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='常规岗位需坚守病房，但资深专家和高年资医生因异地会诊（多点执业）、全国性或国际学术研讨而常有差旅，属于高级别专业交流为主的低频但高质量出行。',r.update_time=NOW() WHERE d.code='travel' AND c.name='临床医生';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='涉及客户现场驻场搭建数据系统的岗位有较高出差需求（如单次驻场1-2个月），但多数总部支持岗无需出差。因项目性质不同，该职业整体出差分化较大。',r.update_time=NOW() WHERE d.code='travel' AND c.name='数据分析师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='以办公室创作为主。会展设计、品牌活动策划等岗位有现场勘察和跟活动需求，会存在偶发的短途、集中出差，但整体非工作常态。',r.update_time=NOW() WHERE d.code='travel' AND c.name='视觉设计师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='除审计、纪委等特殊岗位和参加异地培训外，多数岗位坐班为主，工作地稳定。层级间有差异，但机关整体的平均出差频率在职业光谱中处于低位。',r.update_time=NOW() WHERE d.code='travel' AND c.name='综合管理类公务员';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='工作高度围绕固定校历和课堂，外出多限于短期培训、教研交流或带领学生比赛。虽有校领导及中层岗位出差可能性高，但占大比例的一线教师年均出差频率较低。',r.update_time=NOW() WHERE d.code='travel' AND c.name='中小学教师';
UPDATE gkzh_sszctop_dimension_rank r JOIN gkzh_sszctop_dimension d ON d.dimension_id=r.dimension_id JOIN gkzh_sszctop_career c ON c.career_id=r.career_id SET r.description='工作固定性最强，仅在博物馆展厅内活动。除极少的外出讲解比赛或馆际借展交流，工作无需出差，频率为12个职业中最低',r.update_time=NOW() WHERE d.code='travel' AND c.name='博物馆讲解员';
