-- zycck 基础结构；可重复执行。配置/记录均按活动实例隔离。
-- 规范：所有业务表和字段必须提供中文 COMMENT，便于数据库运维和后续接手。

CREATE TABLE IF NOT EXISTS gkzh_zycck_category (
  category_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '职业大类编号',
  code VARCHAR(32) NOT NULL COMMENT '职业大类唯一编码',
  name VARCHAR(64) NOT NULL COMMENT '职业大类名称',
  description VARCHAR(1000) DEFAULT NULL COMMENT '职业大类说明',
  draw_mode VARCHAR(16) NOT NULL DEFAULT 'fixed' COMMENT '抽题模式：fixed固定抽取，random随机抽取',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '显示顺序，数值越小越靠前',
  status CHAR(1) NOT NULL DEFAULT '0' COMMENT '状态：0正常，1停用',
  create_time DATETIME DEFAULT NULL COMMENT '创建时间',
  update_time DATETIME DEFAULT NULL COMMENT '最后更新时间',
  PRIMARY KEY(category_id),
  UNIQUE KEY uk_zycck_category_code(code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='职业猜猜看职业大类';

CREATE TABLE IF NOT EXISTS gkzh_zycck_career_question (
  career_question_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '职业资料编号，同时作为题目编号',
  category_id BIGINT NOT NULL COMMENT '所属职业大类编号',
  career_name VARCHAR(100) NOT NULL COMMENT '职业名称',
  one_line_intro VARCHAR(500) DEFAULT NULL COMMENT '职业一句话介绍',
  main_work VARCHAR(2000) DEFAULT NULL COMMENT '职业主要工作内容',
  day_example VARCHAR(2000) DEFAULT NULL COMMENT '职业一天工作示例',
  why_exists VARCHAR(2000) DEFAULT NULL COMMENT '职业产生或存在的原因',
  career_image_url VARCHAR(500) DEFAULT NULL COMMENT '职业展示图片地址',
  question_image_url VARCHAR(500) DEFAULT NULL COMMENT '竞猜题目场景图片地址',
  option_a VARCHAR(200) NOT NULL COMMENT '竞猜题A选项文字',
  option_b VARCHAR(200) NOT NULL COMMENT '竞猜题B选项文字',
  option_c VARCHAR(200) NOT NULL COMMENT '竞猜题C选项文字',
  option_d VARCHAR(200) NOT NULL COMMENT '竞猜题D选项文字',
  option_a_career_id BIGINT NOT NULL COMMENT 'A选项关联的职业资料编号',
  option_b_career_id BIGINT NOT NULL COMMENT 'B选项关联的职业资料编号',
  option_c_career_id BIGINT NOT NULL COMMENT 'C选项关联的职业资料编号',
  option_d_career_id BIGINT NOT NULL COMMENT 'D选项关联的职业资料编号',
  correct_option_key CHAR(1) NOT NULL COMMENT '正确选项标识：A、B、C或D',
  explanation VARCHAR(2000) DEFAULT NULL COMMENT '答案解析说明',
  draw_candidate CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否进入抽题候选池：0否，1是',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '同一大类中的显示顺序',
  status CHAR(1) NOT NULL DEFAULT '0' COMMENT '状态：0正常，1停用',
  create_time DATETIME DEFAULT NULL COMMENT '创建时间',
  update_time DATETIME DEFAULT NULL COMMENT '最后更新时间',
  PRIMARY KEY(career_question_id),
  UNIQUE KEY uk_zycck_career(category_id,career_name),
  KEY idx_zycck_question_category(category_id,draw_candidate,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='职业猜猜看职业资料及竞猜题目';

CREATE TABLE IF NOT EXISTS gkzh_zycck_record (
  record_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '参与记录编号',
  school_id BIGINT NOT NULL COMMENT '学校编号',
  instance_id BIGINT NOT NULL COMMENT '活动周实例编号',
  game_id BIGINT NOT NULL COMMENT '活动游戏编号',
  user_id BIGINT NOT NULL COMMENT '平台用户编号',
  student_id BIGINT DEFAULT NULL COMMENT '学生编号',
  department_id BIGINT DEFAULT NULL COMMENT '院系或专业部门编号',
  major VARCHAR(100) DEFAULT NULL COMMENT '专业名称快照',
  gender CHAR(1) DEFAULT NULL COMMENT '性别快照：0男，1女，其他未知',
  game_type VARCHAR(32) NOT NULL DEFAULT 'zycck' COMMENT '游戏类型，固定为zycck',
  status VARCHAR(16) NOT NULL DEFAULT 'participating' COMMENT '参与状态：participating进行中，finished已完成',
  stage VARCHAR(32) NOT NULL DEFAULT 'scanned' COMMENT '当前业务阶段',
  current_question_no INT NOT NULL DEFAULT 0 COMMENT '当前题号',
  question_ids VARCHAR(200) DEFAULT NULL COMMENT '本局抽中的题目编号列表',
  question_order VARCHAR(200) DEFAULT NULL COMMENT '本局题目实际作答顺序',
  career_ids VARCHAR(200) DEFAULT NULL COMMENT '本局关联的职业编号列表',
  category_ids VARCHAR(200) DEFAULT NULL COMMENT '本局关联的职业大类编号列表',
  option_snapshot_json JSON DEFAULT NULL COMMENT '题目和选项快照JSON',
  answer_json JSON DEFAULT NULL COMMENT '学生答案JSON',
  awareness_json JSON DEFAULT NULL COMMENT '学生职业了解程度JSON',
  viewed_career_ids VARCHAR(1000) DEFAULT NULL COMMENT '已查看的职业编号列表',
  exploration_career_ids VARCHAR(1000) DEFAULT NULL COMMENT '进一步探索清单职业编号列表',
  config_version VARCHAR(64) DEFAULT NULL COMMENT '创建记录时使用的游戏配置版本',
  question_start_time DATETIME DEFAULT NULL COMMENT '当前题目开始作答时间',
  question_elapsed_seconds INT NOT NULL DEFAULT 0 COMMENT '当前题目累计作答秒数',
  scan_time DATETIME NOT NULL COMMENT '学生扫码进入游戏时间',
  start_time DATETIME DEFAULT NULL COMMENT '学生正式开始游戏时间',
  finish_time DATETIME DEFAULT NULL COMMENT '学生完成游戏时间',
  create_time DATETIME DEFAULT NULL COMMENT '参与记录创建时间',
  update_time DATETIME DEFAULT NULL COMMENT '参与记录最后更新时间',
  PRIMARY KEY(record_id),
  UNIQUE KEY uk_zycck_record_scope(school_id,instance_id,game_id,user_id),
  KEY idx_zycck_record_instance(instance_id,game_id),
  KEY idx_zycck_record_user(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='职业猜猜看学生参与记录';
