-- 按最终确认的五大职业类别补齐 50 个职业/题目。
UPDATE gkzh_zycck_category SET code='digital_product',name='数字产品与体验类',draw_mode='fixed',sort_order=1 WHERE code='technology';
UPDATE gkzh_zycck_category SET code='digital_content',name='数字内容与创意类',draw_mode='fixed',sort_order=2 WHERE code='health';
UPDATE gkzh_zycck_category SET code='digital_marketing',name='数字营销与商业类',draw_mode='random',sort_order=3 WHERE code='culture';
UPDATE gkzh_zycck_category SET code='professional_service',name='专业服务与知识服务类',draw_mode='random',sort_order=4 WHERE code='management';
UPDATE gkzh_zycck_category SET code='freelance_skill',name='个人技能与自由职业类',draw_mode='random',sort_order=5 WHERE code='nature';
UPDATE gkzh_zycck_category SET draw_mode='fixed' WHERE code IN ('digital_product','digital_content');
UPDATE gkzh_zycck_category SET draw_mode='random' WHERE code IN ('digital_marketing','professional_service','freelance_skill');
DELETE q FROM gkzh_zycck_career_question q JOIN gkzh_zycck_category c ON c.category_id=q.category_id;
DROP TEMPORARY TABLE IF EXISTS tmp_zycck_final;
CREATE TEMPORARY TABLE tmp_zycck_final(category_code VARCHAR(32),career_name VARCHAR(100),intro VARCHAR(500));
INSERT INTO tmp_zycck_final VALUES
('digital_product','产品经理','围绕用户需求规划产品并协调团队交付。'),('digital_product','用户体验研究员','通过访谈、观察和测试研究用户体验。'),('digital_product','交互设计师','设计数字产品的交互流程和使用体验。'),('digital_product','UI设计师','负责数字界面的视觉设计与规范。'),('digital_product','服务设计师','从全流程视角设计服务触点和体验。'),('digital_product','数字孪生设计师','为真实对象构建可交互的数字模型。'),('digital_product','游戏策划师','设计游戏规则、玩法和关卡体验。'),('digital_product','AI产品训练师','整理数据并训练模型满足产品需求。'),('digital_product','低代码开发顾问','用低代码平台帮助客户快速搭建应用。'),('digital_product','智能硬件体验师','测试并优化智能硬件的人机体验。'),
('digital_content','短视频编导','策划、拍摄和制作短视频内容。'),('digital_content','数字内容策划','规划数字内容主题、形式和传播节奏。'),('digital_content','新媒体编辑','编辑图文和视频内容并维护内容渠道。'),('digital_content','视觉设计师','用视觉语言完成品牌和数字内容设计。'),('digital_content','动画设计师','制作二维或三维动画并讲述视觉故事。'),('digital_content','3D建模师','使用三维软件建立物体和场景模型。'),('digital_content','数字插画师','创作适用于屏幕和出版物的数字插画。'),('digital_content','虚拟人设计师','设计虚拟角色的形象、动作和表达。'),('digital_content','游戏美术设计师','为游戏制作角色、场景和界面美术。'),('digital_content','文创产品设计师','将文化元素转化为可销售的创意产品。'),
('digital_marketing','数字营销策划','制定线上营销策略并评估传播效果。'),('digital_marketing','用户增长运营','通过产品和活动提升用户规模与活跃度。'),('digital_marketing','直播运营','策划直播内容、流程和用户转化。'),('digital_marketing','电商运营','运营电商店铺、商品和销售活动。'),('digital_marketing','社群运营','维护用户社群并组织互动和服务。'),('digital_marketing','品牌策划','提炼品牌价值并制定传播方案。'),('digital_marketing','商业数据分析师','分析经营数据并提出商业改进建议。'),('digital_marketing','SEO搜索运营','优化内容和网站以提升搜索曝光。'),('digital_marketing','跨境电商专员','负责跨境商品、平台和客户运营。'),('digital_marketing','内容商务经理','连接内容创作者与商业合作伙伴。'),
('professional_service','数据隐私保护师','帮助组织识别并保护个人数据风险。'),('professional_service','法律科技顾问','用数字工具为法律业务提供解决方案。'),('professional_service','健康管理师','为个人制定健康评估和管理计划。'),('professional_service','在线教育产品顾问','帮助教育机构设计线上产品和课程服务。'),('professional_service','知识产权专员','管理商标、专利和版权等知识产权事务。'),('professional_service','财税顾问','为企业和个人提供财税规划建议。'),('professional_service','生涯规划师','帮助个人认识自我并规划学习与职业方向。'),('professional_service','心理健康服务师','提供心理健康支持、筛查和转介服务。'),('professional_service','企业培训师','设计并实施组织培训与学习项目。'),('professional_service','科普内容顾问','把专业知识转化为易懂的科普内容。'),
('freelance_skill','独立摄影师','以项目制方式完成肖像、商业或纪实摄影。'),('freelance_skill','自由撰稿人','为媒体、品牌或机构独立创作文字内容。'),('freelance_skill','插画接单师','根据客户需求完成定制插画项目。'),('freelance_skill','配音师','为影视、动画、广告或课程提供声音表演。'),('freelance_skill','家庭教育指导师','为家庭提供亲子沟通和教育方法支持。'),('freelance_skill','宠物行为训练师','通过训练改善宠物行为并指导主人。'),('freelance_skill','整理收纳师','帮助客户规划空间并建立收纳习惯。'),('freelance_skill','旅行体验设计师','设计个性化旅行路线和在地体验。'),('freelance_skill','健身教练','根据目标制定训练计划并指导运动。'),('freelance_skill','手工艺设计师','创作并制作具有审美和实用价值的手工艺品。');
INSERT INTO gkzh_zycck_career_question(category_id,career_name,one_line_intro,main_work,day_example,why_exists,option_a,option_b,option_c,option_d,option_a_career_id,option_b_career_id,option_c_career_id,option_d_career_id,correct_option_key,explanation,draw_candidate,sort_order,status,create_time,update_time)
SELECT c.category_id,t.career_name,t.intro,t.intro,CONCAT('围绕',t.career_name,'的典型任务开展工作。'),CONCAT('社会需要',t.career_name,'解决真实问题。'),t.career_name,'产品经理','数字营销策划','独立摄影师',0,0,0,0,'A',CONCAT('正确答案对应的职业是：',t.career_name,'。'),'0',1,'0',NOW(),NOW() FROM tmp_zycck_final t JOIN gkzh_zycck_category c ON c.code=t.category_code
ON DUPLICATE KEY UPDATE one_line_intro=VALUES(one_line_intro),main_work=VALUES(main_work),day_example=VALUES(day_example),why_exists=VALUES(why_exists),option_a=VALUES(option_a),option_b=VALUES(option_b),option_c=VALUES(option_c),option_d=VALUES(option_d),correct_option_key='A',explanation=VALUES(explanation),status='0',update_time=NOW();
DROP TEMPORARY TABLE IF EXISTS tmp_zycck_rank;
CREATE TEMPORARY TABLE tmp_zycck_rank AS SELECT q.career_question_id,q.category_id,q.career_name,(SELECT COUNT(*) FROM gkzh_zycck_career_question x WHERE x.category_id=q.category_id AND x.career_question_id<=q.career_question_id) rn FROM gkzh_zycck_career_question q;
CREATE TEMPORARY TABLE tmp_zycck_rank_b AS SELECT * FROM tmp_zycck_rank;
CREATE TEMPORARY TABLE tmp_zycck_rank_c AS SELECT * FROM tmp_zycck_rank;
CREATE TEMPORARY TABLE tmp_zycck_rank_d AS SELECT * FROM tmp_zycck_rank;
UPDATE gkzh_zycck_career_question q JOIN tmp_zycck_rank s ON s.career_question_id=q.career_question_id JOIN tmp_zycck_rank_b b ON b.category_id=s.category_id AND b.rn=IF(s.rn=10,1,s.rn+1) JOIN tmp_zycck_rank_c d ON d.category_id=s.category_id AND d.rn=IF(s.rn>=9,s.rn-8,s.rn+2) JOIN tmp_zycck_rank_d e ON e.category_id=s.category_id AND e.rn=IF(s.rn>=8,s.rn-7,s.rn+3) SET q.option_a_career_id=s.career_question_id,q.option_b_career_id=b.career_question_id,q.option_c_career_id=d.career_question_id,q.option_d_career_id=e.career_question_id,q.option_a=s.career_name,q.option_b=b.career_name,q.option_c=d.career_name,q.option_d=e.career_name,q.sort_order=s.rn;
UPDATE gkzh_zycck_career_question SET draw_candidate='0';
UPDATE gkzh_zycck_career_question q JOIN (SELECT category_id,MIN(career_question_id) id FROM gkzh_zycck_career_question GROUP BY category_id) x ON x.category_id=q.category_id AND x.id=q.career_question_id SET q.draw_candidate='1';
DROP TEMPORARY TABLE IF EXISTS tmp_zycck_random_candidates;
CREATE TEMPORARY TABLE tmp_zycck_random_candidates AS SELECT x.career_question_id FROM gkzh_zycck_career_question x WHERE x.category_id=(SELECT category_id FROM gkzh_zycck_category WHERE code='digital_marketing') AND (SELECT COUNT(*) FROM gkzh_zycck_career_question y WHERE y.category_id=x.category_id AND y.career_question_id<=x.career_question_id)<=3;
UPDATE gkzh_zycck_career_question q JOIN tmp_zycck_random_candidates r ON r.career_question_id=q.career_question_id SET q.draw_candidate='1';
DROP TEMPORARY TABLE IF EXISTS tmp_zycck_random_candidates;
CREATE TEMPORARY TABLE tmp_zycck_random_candidates AS SELECT x.career_question_id FROM gkzh_zycck_career_question x JOIN gkzh_zycck_category c ON c.category_id=x.category_id WHERE c.draw_mode='random' AND (SELECT COUNT(*) FROM gkzh_zycck_career_question y WHERE y.category_id=x.category_id AND y.career_question_id<=x.career_question_id)<=3;
UPDATE gkzh_zycck_career_question q JOIN tmp_zycck_random_candidates r ON r.career_question_id=q.career_question_id SET q.draw_candidate='1';
