-- 使用已整理的 PNG 素材更新心愿橱窗图案图片路径
UPDATE `xycc_pattern`
SET `img_url` = CASE `description`
  WHEN '激光测距仪' THEN '/static/xycc/pattern/jiguancejuyi.png'
  WHEN '户外手表' THEN '/static/xycc/pattern/huwaishoubiao.png'
  WHEN '房车' THEN '/static/xycc/pattern/fangche.png'
  WHEN '跑步机' THEN '/static/xycc/pattern/paobuji.png'
  WHEN '公路自行车' THEN '/static/xycc/pattern/zixingche.png'
  WHEN '鱼竿' THEN '/static/xycc/pattern/yugan.png'
  WHEN '天文望远镜' THEN '/static/xycc/pattern/wangyuanjing.png'
  WHEN '罗盘' THEN '/static/xycc/pattern/luopan.png'
  WHEN '智能手机' THEN '/static/xycc/pattern/shouji.png'
  WHEN '放大镜' THEN '/static/xycc/pattern/fadajing.png'
  WHEN '3D打印机' THEN '/static/xycc/pattern/dayinji.png'
  WHEN '火箭模型' THEN '/static/xycc/pattern/huojian.png'
  WHEN '棋盘' THEN '/static/xycc/pattern/qipan.png'
  WHEN '画板、画笔' THEN '/static/xycc/pattern/huaban.png'
  WHEN '钢琴' THEN '/static/xycc/pattern/gangqin.png'
  WHEN '毛笔' THEN '/static/xycc/pattern/maobi.png'
  WHEN '汉服' THEN '/static/xycc/pattern/hanfu.png'
  WHEN '成人乐高' THEN '/static/xycc/pattern/lego.png'
  WHEN '钻石' THEN '/static/xycc/pattern/zuanshi.png'
  WHEN '演唱会门票' THEN '/static/xycc/pattern/menpiao.png'
  WHEN '茶具' THEN '/static/xycc/pattern/chaju.png'
  WHEN '咖啡机' THEN '/static/xycc/pattern/kafeiji.png'
  WHEN '公文包' THEN '/static/xycc/pattern/gongwenbao.png'
  WHEN '平板电脑' THEN '/static/xycc/pattern/pingban.png'
  WHEN '商务旅行箱' THEN '/static/xycc/pattern/lvxingxiang.png'
  WHEN '无线鼠标' THEN '/static/xycc/pattern/Mouse.png'
  WHEN '录音笔' THEN '/static/xycc/pattern/luyinbi.png'
  WHEN '拍立得' THEN '/static/xycc/pattern/pailide.png'
  WHEN '移动硬盘' THEN '/static/xycc/pattern/yingpan.png'
  WHEN '无线键盘' THEN '/static/xycc/pattern/jianpan.png'
  ELSE `img_url`
END;
