UPDATE `xycc_pattern`
SET `material_url` = CASE `description`
  WHEN '激光测距仪' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/激光测距仪.eps'
  WHEN '户外手表' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/户外手表.eps'
  WHEN '房车' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/房车.eps'
  WHEN '跑步机' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/跑步机.eps'
  WHEN '公路自行车' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/公路自行车.eps'
  WHEN '鱼竿' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/鱼竿.eps'
  WHEN '天文望远镜' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/天文望远镜.eps'
  WHEN '罗盘' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/罗盘.eps'
  WHEN '智能手机' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/智能手机.eps'
  WHEN '放大镜' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/放大镜.eps'
  WHEN '3D打印机' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/3D打印机.eps'
  WHEN '火箭模型' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/火箭模型.eps'
  WHEN '棋盘' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/围棋.eps'
  WHEN '画板、画笔' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/画板和画笔套装.eps'
  WHEN '钢琴' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/钢琴.eps'
  WHEN '毛笔' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/毛笔.eps'
  WHEN '汉服' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/汉服.eps'
  WHEN '成人乐高' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/成人乐高.svg'
  WHEN '钻石' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/钻石.eps'
  WHEN '演唱会门票' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/演唱会门票.eps'
  WHEN '报纸' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/报纸.eps'
  WHEN '茶具' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/茶具.eps'
  WHEN '咖啡机' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/咖啡机.eps'
  WHEN '黄金首饰' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/黄金首饰.eps'
  WHEN '商务投影仪' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/商务投影仪.eps'
  WHEN '公文包' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/公文包.eps'
  WHEN '平板电脑' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/平板电脑.eps'
  WHEN '职业装' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/职业装.eps'
  WHEN '个人名片' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/个人名片.eps'
  WHEN '商务旅行箱' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/商务旅行箱.eps'
  WHEN '蓝牙音响' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/蓝牙音箱.eps'
  WHEN '无线鼠标' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/无线鼠标.eps'
  WHEN '录音笔' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/录音笔.eps'
  WHEN '拍立得' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/拍立得.eps'
  WHEN '移动硬盘' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/移动硬盘.eps'
  WHEN '无线键盘' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/无线键盘.eps'
  ELSE `material_url`
END;

UPDATE `xycc_pattern`
SET `img_url` = CASE `description`
  WHEN '激光测距仪' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/jiguancejuyi.png'
  WHEN '户外手表' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/huwaishoubiao.png'
  WHEN '房车' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/fangche.png'
  WHEN '跑步机' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/paobuji.png'
  WHEN '公路自行车' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/zixingche.png'
  WHEN '鱼竿' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/yugan.png'
  WHEN '天文望远镜' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/wangyuanjing.png'
  WHEN '罗盘' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/luopan.png'
  WHEN '智能手机' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/shouji.png'
  WHEN '放大镜' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/fadajing.png'
  WHEN '3D打印机' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/dayinji.png'
  WHEN '火箭模型' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/huojian.png'
  WHEN '棋盘' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/qipan.png'
  WHEN '画板、画笔' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/huaban.png'
  WHEN '钢琴' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/gangqin.png'
  WHEN '毛笔' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/maobi.png'
  WHEN '汉服' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/hanfu.png'
  WHEN '成人乐高' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/lego.png'
  WHEN '钻石' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/zuanshi.png'
  WHEN '演唱会门票' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/menpiao.png'
  WHEN '茶具' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/chaju.png'
  WHEN '咖啡机' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/kafeiji.png'
  WHEN '公文包' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/gongwenbao.png'
  WHEN '平板电脑' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/pingban.png'
  WHEN '商务旅行箱' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/lvxingxiang.png'
  WHEN '无线鼠标' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/Mouse.png'
  WHEN '录音笔' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/luyinbi.png'
  WHEN '拍立得' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/pailide.png'
  WHEN '移动硬盘' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/yingpan.png'
  WHEN '无线键盘' THEN 'https://zhiye.sxgkzh.cn/imgs/xycc/png/jianpan.png'
  ELSE `img_url`
END;
