-- 心愿橱窗源素材路径
UPDATE `xycc_pattern`
SET `material_url` = CASE `description`
  WHEN '激光测距仪' THEN '/static/xycc/materials/激光测距仪.eps'
  WHEN '户外手表' THEN '/static/xycc/materials/户外手表.eps'
  WHEN '房车' THEN '/static/xycc/materials/房车.eps'
  WHEN '跑步机' THEN '/static/xycc/materials/跑步机.eps'
  WHEN '公路自行车' THEN '/static/xycc/materials/公路自行车.eps'
  WHEN '鱼竿' THEN '/static/xycc/materials/鱼竿.eps'
  WHEN '天文望远镜' THEN '/static/xycc/materials/天文望远镜.eps'
  WHEN '罗盘' THEN '/static/xycc/materials/罗盘.eps'
  WHEN '智能手机' THEN '/static/xycc/materials/智能手机.eps'
  WHEN '放大镜' THEN '/static/xycc/materials/放大镜.eps'
  WHEN '3D打印机' THEN '/static/xycc/materials/3D打印机.eps'
  WHEN '火箭模型' THEN '/static/xycc/materials/火箭模型.eps'
  WHEN '棋盘' THEN '/static/xycc/materials/围棋.eps'
  WHEN '画板、画笔' THEN '/static/xycc/materials/画板和画笔套装.eps'
  WHEN '钢琴' THEN '/static/xycc/materials/钢琴.eps'
  WHEN '毛笔' THEN '/static/xycc/materials/毛笔.eps'
  WHEN '汉服' THEN '/static/xycc/materials/汉服.eps'
  WHEN '成人乐高' THEN '/static/xycc/materials/成人乐高.svg'
  WHEN '钻石' THEN '/static/xycc/materials/钻石.eps'
  WHEN '演唱会门票' THEN '/static/xycc/materials/演唱会门票.eps'
  WHEN '报纸' THEN '/static/xycc/materials/报纸.eps'
  WHEN '茶具' THEN '/static/xycc/materials/茶具.eps'
  WHEN '咖啡机' THEN '/static/xycc/materials/咖啡机.eps'
  WHEN '黄金首饰' THEN '/static/xycc/materials/黄金首饰.eps'
  WHEN '商务投影仪' THEN '/static/xycc/materials/商务投影仪.eps'
  WHEN '公文包' THEN '/static/xycc/materials/公文包.eps'
  WHEN '平板电脑' THEN '/static/xycc/materials/平板电脑.eps'
  WHEN '职业装' THEN '/static/xycc/materials/职业装.eps'
  WHEN '个人名片' THEN '/static/xycc/materials/个人名片.eps'
  WHEN '商务旅行箱' THEN '/static/xycc/materials/商务旅行箱.eps'
  WHEN '蓝牙音响' THEN '/static/xycc/materials/蓝牙音箱.eps'
  WHEN '无线鼠标' THEN '/static/xycc/materials/无线鼠标.eps'
  WHEN '录音笔' THEN '/static/xycc/materials/录音笔.eps'
  WHEN '拍立得' THEN '/static/xycc/materials/拍立得.eps'
  WHEN '移动硬盘' THEN '/static/xycc/materials/移动硬盘.eps'
  WHEN '无线键盘' THEN '/static/xycc/materials/无线键盘.eps'
  ELSE `material_url`
END;
